# Generated by Django 5.0.6 on 2024-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_details_age_alter_user_details_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
